/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fabTimAlex.nonogram;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author fbnhe
 */
public class NonogramUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NonogramUI.class.getName());

    /**
     * Creates new form NonogramUI
     */

    
    private JTextField rowsField;
    private JTextField colsField;
    private JPanel gridPanel;
    private Nonogram currentNonogram;

    public NonogramUI() {
            initComponents();
        setTitle("Nonogram Generator & Solver");
        setSize(900, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        add(createControlPanel(), BorderLayout.NORTH);

        gridPanel = new JPanel();
        add(new JScrollPane(gridPanel), BorderLayout.CENTER);

        setVisible(true);
    }

    private JPanel createControlPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout());

        panel.add(new JLabel("Lignes :"));
        rowsField = new JTextField("10", 5);
        panel.add(rowsField);

        panel.add(new JLabel("Colonnes :"));
        colsField = new JTextField("10", 5);
        panel.add(colsField);

        JButton generateBtn = new JButton("Générer");
        generateBtn.addActionListener(e -> generateNonogram());
        panel.add(generateBtn);

        JButton solveBtn = new JButton("Résoudre");
        solveBtn.addActionListener(e -> solveNonogram());
        panel.add(solveBtn);

        return panel;
    }

    private void generateNonogram() {
        try {
            int rows = Integer.parseInt(rowsField.getText());
            int cols = Integer.parseInt(colsField.getText());

            currentNonogram = new Nonogram(rows, cols);
            displayGrid(currentNonogram.getgrille());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage());
        }
    }

    private void solveNonogram() {
        if (currentNonogram == null) {
            JOptionPane.showMessageDialog(this, "Génère d'abord un nonogram !");
            return;
        }

        NonogramSolver solver = new NonogramSolver(
                currentNonogram.getligneIndice(),
                currentNonogram.getcolonneIndice()
        );

        boolean[][] solved = solver.solve();

        if (solved == null) {
            JOptionPane.showMessageDialog(this, "Aucune solution trouvée.");
        } else {
            displayGrid(solved);
        }
    }

    private void displayGrid(boolean[][] grid) {
        gridPanel.removeAll();

        int rows = grid.length;
        int cols = grid[0].length;

        gridPanel.setLayout(new GridLayout(rows, cols));

        for (int r = 0; r < rows; r++) {
            for (int c = 0; c < cols; c++) {
                JPanel cell = new JPanel();
                cell.setPreferredSize(new Dimension(20, 20));
                cell.setBackground(grid[r][c] ? Color.BLACK : Color.WHITE);
                cell.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                gridPanel.add(cell);
            }
        }

        gridPanel.revalidate();
        gridPanel.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(NonogramUI::new);
        java.awt.EventQueue.invokeLater(() -> new NonogramUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
